- name: Checkout code
  uses: actions/checkout@v4

- name: Create environment.yml if missing
  run: |
    if [ ! -f environment.yml ]; then
      echo "Creating basic environment.yml file"
      cat > environment.yml << EOF
    name: test-env
    channels:
      - conda-forge
      - defaults
    dependencies:
      - python=3.10
      - pip
      - pip:
        - pytest
        - pytest-cov
        - flake8
    EOF
    fi

- name: Setup Miniconda (with mamba)
  uses: conda-incubator/setup-miniconda@v2
  with:
    python-version: ${{ matrix.python-version }}
    # ... باقي الإعدادات
