name: Python package using Conda

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']   # يمكن إضافة إصدارات أخرى مثل '3.8','3.9'
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Miniconda (with mamba)
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          use-mamba: true
          activate-environment: ci
          environment-file: environment.yml
          auto-activate-base: false

      - name: Cache conda packages
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.CONDA }}/pkgs
            ~/.conda/pkgs
          key: conda-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('environment.yml') }}
          restore-keys: |
            conda-${{ runner.os }}-${{ matrix.python-version }}-

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/requirements*.txt', '**/pyproject.toml', '**/setup.py') }}
          restore-keys: |
            pip-${{ runner.os }}-${{ matrix.python-version }}-

      - name: Create and activate environment
        run: |
          mamba env create -f environment.yml --force
          conda activate ci

      - name: Install package in development mode
        run: |
          pip install -e . --no-deps

      - name: Display environment info
        run: |
          python --version
          pip --version
          conda info
          conda list

      - name: Lint with flake8
        run: |
          # تثبيت flake8 إذا لم يكن موجوداً
          pip install flake8
          # فحص الأخطاء الحرجة (توقف عند وجودها)
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # فحص باقي الأخطاء (تحذيرات فقط)
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests with pytest
        run: |
          pip install pytest pytest-cov
          mkdir -p reports
          pytest --junitxml=reports/junit.xml --cov=./ --cov-report=xml:reports/coverage.xml --cov-report=html:reports/htmlcov

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.python-version }}
          path: |
            reports/
            !reports/htmlcov/

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-html-${{ matrix.python-version }}
          path: reports/htmlcov/

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run security scan
        run: |
          pip install bandit safety
          bandit -r . -f html -o reports/bandit.html || true
          safety check --json --output reports/safety.json || true

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: reports/
