name: Python package using Conda

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Miniconda with Mamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: false
          miniforge-version: latest
          use-mamba: true
          activate-environment: test-env
          auto-activate-base: false
          channels: conda-forge
          channel-priority: strict

      - name: Install Python dependencies
        run: |
          mamba install -y numpy pandas
          pip install pytest pytest-cov flake8

      - name: Install package in development mode
        run: |
          pip install -e .

      - name: Run linting and tests
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          mkdir -p test-reports
          pytest --junitxml=test-reports/junit.xml --cov=./ --cov-report=xml:test-reports/coverage.xml -v
